# lexik_jwt_authentication:
#     secret_key: '%env(resolve:JWT_SECRET_KEY)%'
#     public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
#     pass_phrase: '%env(JWT_PASSPHRASE)%'

# config/packages/lexik_jwt_authentication.yaml

# lexik_jwt_authentication:
#     secret_key: '%env(APP_SECRET)%'
#     public_key: '%env(JWT_PUBLIC_KEY)%'
#     pass_phrase: '%env(JWT_PASSPHRASE)%'
#     token_ttl: '%env(JWT_TOKEN_TTL)%'

# config/packages/lexik_jwt_authentication.yaml

lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/config/jwt/private.pem' # Chemin vers la clé privée
    public_key_path:  '%kernel.project_dir%/config/jwt/public.pem'  # Chemin vers la clé publique
    pass_phrase:      'root'                       # Passphrase utilisée pour générer la paire de clés (optionnelle)
    token_ttl:        3600                                         # Durée de validité du token en secondes
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci # Utiliser le bon service d'encodage
